import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
  scrollContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative'
  },
  container: {
    backgroundColor: '#FFF',
    height: '100%',
    width: '100%',
    paddingTop: 0,
    paddingLeft: 10,
    paddingBottom: 80,
    paddingRight: 10,
    marginTop: 5,
    position: 'relative',
    justifyContent: 'center',
  },
  form: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 20,
    position: 'relative'
  },
  img: {
    width: 180,
    height: 180,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 90,
  },
  removeText:{
    marginTop: 5,
    marginBottom: 20,
    color: '#e53d3d',
    fontSize: 14,
  },
  imgChangeText: {
    marginTop: 5,
    marginBottom: 20,
    color: '#bbb',
    fontSize: 14,
    // textDecorationLine: 'underline'
  },
  loadingImg: {
    width: 50,
    height: 50,
    marginTop: 30,
  },
  inputContainer: {
    flexDirection: 'row',
    height: 50,
    width: '90%',
    borderWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 0,
    backgroundColor: 'transparent',
    borderRadius: 4,
    marginBottom: 10
  },
  input: {
    flex: 1,
    height: 50,
    paddingBottom: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 15,
    paddingRight: 0,
    backgroundColor: '#f5f5f5',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    color: '#aaa'
  },
  emailIcon: {
    height: 50,
    width: 50,
    borderRightWidth: 2,
    borderColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    backgroundColor: '#f5f5f5',
  },
  passwordIcon: {
    height: 50,
    width: 50,
    borderRightWidth: 2,
    borderColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    backgroundColor: '#f5f5f5',
  },
  updateButton: {
    backgroundColor: "#15BDD8",
    paddingTop: 15,
    paddingRight: 12,
    paddingBottom: 15,
    paddingLeft: 12,
    alignSelf: "center",
    borderRadius: 4,
    width: '70%',
    marginTop: 30,
  },
  passButtonContainer: {
    flexDirection: 'row',
  },
  updatePasswordButton: {
    backgroundColor: "#15BDD8",
    paddingTop: 15,
    paddingRight: 12,
    paddingBottom: 15,
    paddingLeft: 12,
    alignSelf: "center",
    borderRadius: 4,
    width: '40%',
    marginTop: 28,
    marginLeft: 10,
    marginRight: 10,
  },
  cancelPasswordButton: {
    backgroundColor: "#79dbea",
    paddingTop: 15,
    paddingRight: 12,
    paddingBottom: 15,
    paddingLeft: 12,
    alignSelf: "center",
    borderRadius: 4,
    width: '40%',
    marginTop: 28,
    marginLeft: 10,
    marginRight: 10,
  },
  updateText: {
    color: '#FFF',
    textAlign: 'center',
    fontSize: 18
  },
  passwordBoxContainer: {
    flex: 1,
    height: 50,
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    paddingRight: 5
  },
  passwordText: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 10,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 15,
    paddingRight: 0,
    color: '#bbb',
    backgroundColor: '#fff',
    lineHeight: 35,
    fontSize: 20
  },
  editIcon: {
    height: 40,
    width: 40,
    borderWidth: 1,
    borderColor: '#d7d7d7',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
  },
});
